### ISSUE TITLE
Review gitlab.rb Template

### ISSUE THREAD

**Issue by tobru** [vshn/puppet-gitlab#103]
Gitlab has progressed a lot in the last months. The file [templates/gitlab.rb.erb](https://github.com/vshn/puppet-gitlab/blob/master/templates/gitlab.rb.erb) needs to be revised and aligned to the template found in [Omnibus](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template).

**Comment by james-powis** [comment]
doing some grep foo and looking at the diff from HEAD > omnibus 8.0 the following 2 groupings are not supported currently by this module:

+# sentinel['bind'] = '0.0.0.0'
+# sentinel['port'] = 26379
+# sentinel['quorum'] = 1
+# sentinel['down_after_milliseconds'] = 10000
+# sentinel['failover_timeout'] = 60000
+# sidekiq_cluster['enable'] = false
+# sidekiq_cluster['ha'] = false
+# sidekiq_cluster['log_directory'] = "/var/log/gitlab/sidekiq-cluster"
+# sidekiq_cluster['interval'] = 5 # The number of seconds to wait between worker checks
+# sidekiq_cluster['queue_groups'] = [

**Comment by james-powis** [comment]
best I can tell every other config directive is covered by the existing template.

**Comment by tobru** [comment]
Thanks! It's not just adding parameters, but also removing deprecated parameters... Will hopefully work on this over the next weeks.

**Comment by matonb** [comment]
Would these parameters fit in this category ?

```
gitlab_rails['backup_path'] = <path>
git_data_dirs({"default" => "<path>"})
```

**Comment by tobru** [comment]
> Would these parameters fit in this category ?

Yes =) See also #110

**Comment by davidgubler** [comment]
All the configuration options mentioned above should be supported now. I recently added the missing git_data_dirs (thanks to Corey Osman) and sidekiq_cluster options.

**Comment by LongLiveCHIEF** [comment]
So it turns out that `git_data_dirs` is _currently_ misdocumented. The correct hash for this should look like:

```
#correct
git_data_dirs({'default' => {'path' => '/git/data/path'}})

#incorrect
git_data_dirs({'default' => '/git/data/path'})
```

see: https://gitlab.com/gitlab-org/gitlab-ee/issues/4040#note_54368948
