### ISSUE TITLE
Feature: re-enable signup disable

### ISSUE THREAD

**Issue by cdenneen** [vshn/puppet-gitlab#112]
In omnibus this was deprecated but using puppet manually configuring options via UI probably isn't the best solution:

```
7.9.0

DEPRECATION: 'gitlab_signup_enabled', 'gitlab_signin_enabled', 'gitlab_default_projects_limit', 'gravatar_enabled' are deprecated, settings can be changed in admin section of GitLab UI
```

**Comment by tobru** [comment]
I have a hard time to understand what you want to say. Could you please add some more information here or would you even create a pull request?

**Comment by hmw42** [comment]
I think the OP has the same problem I stumbled upon today. Configuration options like gitlab_signup_enabled can't be customised via /etc/gitlab/gitlab.rb anymore. Ways (I know about) of setting such options are using the web service or the database cmd line client (or the GUI ;)). I haven't found out yet, how the vendor thinks about implementing unattended installs. It would be nice if there is an 'easy' way.

**Comment by tobru** [comment]
So I'll close this issue for now, there is nothing we can do currently.
