### ISSUE TITLE
registry_external_url not recognised in hiera

### ISSUE THREAD

**Issue by kalischt** [vshn/puppet-gitlab#113]
Can this be confirmed as working or not?

Every hiera directive for gitlab.rb I need works for me except
gitlab::registry_external_url: 'somedomain.com:4567'
and 
gitlab::registry_nginx:
  ssl_certificate: '/etc/gitlab/ssl/somedomain.com.crt'
  ssl_certificate_key: '/etc/gitlab/ssl/somedomain.com.key'

Before I keep on digging with my local instance I need to know that it does actually work.

thanks.

**Comment by davidgubler** [comment]
Hi kalischt,

We use all three of these configuration options through a wrapper module and they work fine, thus I see no reason why they should not work with Hiera. But since this is an old issue I assume you figured it out by now?
