### ISSUE TITLE
Registry Configuration incorrectly formatted

### ISSUE THREAD

**Issue by pcfens** [vshn/puppet-gitlab#127]
After switching to commit 5c1d251 in my puppetfile (I really wanted various exporter support) I got the following (sanitized) diff:
```
-registry['storage'] = {"s3"=>{"accesskey"=>"myaccesskey", "bucket"=>"registry", "region"=>"us-east-1", "secretkey"=>"asupersecretkeythatisntsharedongithub"}}
+registry['storage'] = {"s3"=>{"accesskey"=>"'myaccesskey'", "bucket"=>"'registry'", "region"=>"'us-east-1'", "secretkey"=>"'asupersecretkeythatisntsharedongithub'"}}
```

The extra single quotes around each string have broken the registry storage configuration. Some strings are provided from hiera, but some of them (like region and bucket name) are hard coded in the manifest.

I was running version 1.11.0 from the forge before the change. I'm using puppetserver 2.7.2 and Puppet 4.9.4

**Comment by andrekeller** [comment]
https://github.com/vshn/puppet-gitlab/pull/125 should fix this. Can you verify?

**Comment by pcfens** [comment]
It does - this is a duplicate then.

Thanks!
