### ISSUE TITLE
Add parameter to allow to skip auto migrations

### ISSUE THREAD

**Issue by slinger987** [vshn/puppet-gitlab#132]
In the case of an HA setup, there is no need to run the auto migrations on all servers and the documentation specifies that the /etc/gitlab/skip-auto-migrations file sshould be created to prevent database backups on an RPM upgrade.  There is an option to prevent the rails to perform the migrations with 'gitlab_rails['auto_migrate'] = false' in gitlab.rb, but this doesn't help during the package upgrade.  More information on the HA setup documenation:

https://docs.gitlab.com/ce/administration/high_availability/gitlab.html

**Comment by tobru** [comment]
Would you mind to create a PR?

**Comment by davidgubler** [comment]
49f900b58bfaa539cd1145b8fb38ff1fea2a692a adds this functionality.
