### ISSUE TITLE
Unable to disable prometheus monitoring due to template

### ISSUE THREAD

**Issue by doomnuggets** [vshn/puppet-gitlab#135]
There doesn't seem to be a way to disable prometheus with the current template.
We are only able to configure prometheus options prefixed with `prometheus`, but to disable it we need to prefix it with `prometheus_monitoring`.

See: https://docs.gitlab.com/ee/administration/monitoring/prometheus/#configuring-prometheus

**Comment by doomnuggets** [comment]
Might be related to #103 ...

**Comment by davidgubler** [comment]
393ec4e16365aba0932e15686f066bc8a6b646db should take care of this.
