### ISSUE TITLE
Different directory name inside the Forge package

### ISSUE THREAD

**Issue by xorpaul** [vshn/puppet-gitlab#151]
Hi there,

I'm currently having problems using your 1.15.0 Forge package with my r10k clone (https://github.com/xorpaul/g10k), because it doesn't have the same directory name pattern than all other Forge packages.

It also look like that this Forge package was probably not generate with the standard `puppet module build` as described here https://docs.puppet.com/puppet/latest/modules_publishing.html#build-your-module

```
$ cd /tmp/5
$ wget https://forgeapi.puppetlabs.com/v3/files/vshn-gitlab-1.15.0.tar.gz
$ tar tfz vshn-gitlab-1.15.0.tar.gz
puppet-gitlab-1.15.0/   <-------- note the name
...
$ tar xfz vshn-gitlab-1.15.0.tar.gz
$ cd puppet-gitlab-1.15.0/
$ puppet module build .
Notice: Building /tmp/5/puppet-gitlab-1.15.0 for release
Module built: /tmp/5/puppet-gitlab-1.15.0/pkg/vshn-gitlab-1.15.0.tar.gz
$ tar tfz /tmp/5/puppet-gitlab-1.15.0/pkg/vshn-gitlab-1.15.0.tar.gz
vshn-gitlab-1.15.0/   <-------- note the name
...
```

Building your module with  `puppet module build` does create the correct directory name `vshn-gitlab-1.15.0/` inside the package, but the currently uploaded package does have a directory `puppet module build` inside.

Did you build your package with `puppet module build` or with something else?

I'm not entirely sure if the Puppetlabs Forge should be validating uploaded packages for this stuff, but I'll open a FORGE ticket and ask them.

Edit: https://tickets.puppetlabs.com/browse/FORGE-386

**Comment by davidgubler** [comment]
Hi,

Sorry about that. I just rebuilt the package and released 1.15.1, which should fix that. Does it work now?

**Comment by xorpaul** [comment]
Yes, it does work now.

Just out of interest, how did you build the previous package? Simply with `tar`?

**Comment by davidgubler** [comment]
Basically yes, I downloaded the .tar.gz from Github. Why that doesn't work with forge is beyond me. Anyway, thanks for the bug report!

**Comment by xorpaul** [comment]
It does work with the Forge, just not with my caching method :)

As far as I can tell, you did nothing wrong, just different. ;)

I'll leave the FORGE ticket open, so that they can take a statement about whether such a release is valid or invalid in their eyes.
