### ISSUE TITLE
Deploy current version of GitLab Runner

### ISSUE THREAD

**Issue by djjudas21** [vshn/puppet-gitlab#166]
This module is installing an old version of GitLab Runner (i.e. GitLab Ci Multi Runner). It should install GitLab Runner according to https://docs.gitlab.com/runner/install/linux-repository.html#upgrading-to-gitlab-runner-10

**Comment by djjudas21** [comment]
I'm starting work on implementing this

**Comment by djjudas21** [comment]
This is now ready to merge in #167

**Comment by ta5ae** [comment]
Thanks @djjudas21 This looks useful.  Hopefully, it will be accepted soon, seems to pass tests.

**Comment by KlavsKlavsen** [comment]
would be VERY nice.. as current gitlab 10.6 - has some incompatabilities with gitlab-ci-multi-runner 9.5.1 :(

**Comment by LongLiveCHIEF** [comment]
@KlavsKlavsen we _did_ merge. Are you using the latest release of this module?

**Comment by KlavsKlavsen** [comment]
My bad - my VCS played tricks on me when I tested :( it works now :)
