### ISSUE TITLE
Not working on RHEL7?

### ISSUE THREAD

**Issue by jantman** [vshn/puppet-gitlab#17]
I'm having some issues with this module on RHEL (not CentOS, real RHEL).

This module defines the repo ``baseurl`` as ``https://packages.gitlab.com/gitlab/gitlab-ce/el/$releasever/$basearch``

However, on real RHEL, that evaluates as ``https://packages.gitlab.com/gitlab/gitlab-ce/el/7Server/x86_64/``, however ``https://packages.gitlab.com/gitlab/gitlab-ce/el/7Server/x86_64/repodata/repomd.xml`` is 404.

It seems to me that when calculating the repository URL on RedHat-based systems, the module should probably just use the OS major release in Puppet, instead of relying on ``$releasever`` in yum.

**Comment by tobru** [comment]
This is fixed in the next release: https://github.com/vshn/puppet-gitlab/pull/14

**Comment by jantman** [comment]
Oops, I'm sorry. I'll pull in master...
