### ISSUE TITLE
Question: Would this module work with puppet 3.6.2?

### ISSUE THREAD

**Issue by mikec-bullhorn** [vshn/puppet-gitlab#20]
We were running spuder's gitlab module, and really want to leap to this module, but we are running puppet enterprise 3.6.2. Upgrading is on the roadmap, but not in the immediate future. Is it possible that the module is compatible with 3.6.2, but untested? Or did you use some 3.7-specific functionality (which is what I'm guessing).

**Comment by tobru** [comment]
Just give it a try, I'm not really sure if it runs on older versions than 3.7, but maybe it does.
Would be nice to have a feedback from you, also if it runs (so I can adjust the version requirements). If it doesn't run, we can try to get it working, just put the error message into this issue.

**Comment by spielkind** [comment]
Currently it seems that at least puppet 3.7 is required due to this bug:
https://tickets.puppetlabs.com/browse/PUP-1597

A workaround would be to change the init.pp (contain ::gitlab...) code.
```
diff --git a/manifests/init.pp b/manifests/init.pp
index d266237..3fe823c 100644
--- a/manifests/init.pp
+++ b/manifests/init.pp
@@ -247,8 +247,8 @@ class gitlab (
   class { '::gitlab::config': } ~>
   class { '::gitlab::service': }
 
-  contain ::gitlab::install
-  contain ::gitlab::config
-  contain ::gitlab::service
+  contain gitlab::install
+  contain gitlab::config
+  contain gitlab::service
 
 }
```
I would appreciate it to support the default puppet version of Ubuntu 14.04 (3.4.3).
