### ISSUE TITLE
Add CI multi runner installation and configuration

### ISSUE THREAD

**Issue by tobru** [vshn/puppet-gitlab#21]
Add manifests to install and configure Gitlab CI multi runner: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner

**Comment by tobru** [comment]
More information here: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/docs/install/linux-repository.md

**Comment by maetthu-indermuehle** [comment]
I did a pull request for a basic implementation to install Gitlab CI Multirunners.

It has some big Limitations:
* Only tested on Ubuntu 14.04 - And will not work on other distributions than Ubuntu
* Runners can't be deleted from puppet
* Runners that are deleted from the GUI are not recreated
* The Implementation requires Hiera to work
  * Extend testing
