### ISSUE TITLE
Add parameter for Mattermost

### ISSUE THREAD

**Issue by clauded** [vshn/puppet-gitlab#26]
Version 7.14 of Gitlab now supports Mattermost (http://doc.gitlab.com/omnibus/gitlab-mattermost/). A new parameter must be specified in /etc/gitlab/gitlab.rb:

mattermost_external_url 'http://mattermost.example.com'

This parameter should be added to the template and the init module. Maybe a hash of parameters would be nice so it could handle future new parameters.

**Comment by tobru** [comment]
yes, that's already on my list. will be done in the next days
