### ISSUE TITLE
gitlab version support

### ISSUE THREAD

**Issue by cdenneen** [vshn/puppet-gitlab#32]
Will there be Version support in the module?
Currently latest works but see few caveats:
1. if someone wants to lock to a particular version and not update
2. with a version parameter you can update on next puppet run, now you have to do a full "update" at the system level

**Comment by tobru** [comment]
It's already there, just set `package_ensure` to the version string of the package. F.e. to `8.0.3-ce.1` to install this particular version. Upgrading to a newer version is just as easy as bumping this version string. To see a list of available packages, have a look at f.e. https://packages.gitlab.com/gitlab/gitlab-ce
