### ISSUE TITLE
RHEL 6.7 baseurl for yum repo expands incorrectly

### ISSUE THREAD

**Issue by billyrayvalentine** [vshn/puppet-gitlab#42]
On at least Red Hat Enterprise Linux Server release 6.7 (Santiago): The baseurl in /etc/yum.repos.d/gitlab_official.repo exands to:
https://packages.gitlab.com/gitlab/gitlab-ce/el/6Server/x86_64/repodata/repomd.xml - which is incorrect.
It should expand to:
https://packages.gitlab.com/gitlab/gitlab-ce/el/6/x86_64/repodata/repomd.xml

Tested on v1.7.0

**Comment by tobru** [comment]
Probably related to #41

**Comment by tobru** [comment]
Could you please verify if this issue still exists with the latest release `1.7.1`?

**Comment by tobru** [comment]
As I didn't hear back any news on this issue, I'll close it right now. Feel free to open a new one or reopen this.
