### ISSUE TITLE
yum repo is incompatible for Amazon Linux 

### ISSUE THREAD

**Issue by cagriersen** [vshn/puppet-gitlab#46]
Although Amazon Linux is based on RHEL, they're using different release naming schema than RHEL and therefor this module seems incompatible for Amazon AMI.

I think, OS selection case should be modified as includes Amazon Linux $::operatingsystemmajrelease value.

Here is an example facter output from an Amazon AMI:

<pre>operatingsystem => Amazon
operatingsystemmajrelease => 2015
operatingsystemrelease => 2015.09</pre>

**Comment by tobru** [comment]
Thanks for your suggestion. Would you mind creating a tested PR for this? That would make things easier as I don't have access atm to an Amazon AMI to test it.

**Comment by cagriersen** [comment]
Hi again, 

I've just modified the code -in a dirty way- to quick fixing:

<pre>
        if ($::operatingsystem == 'Redhat' and ($::operatingsystemmajrelease == '6' or $::operatingsystemmajrelease == '7')) {
          $releasever = $::operatingsystemmajrelease
        } elsif ($::operatingsystem == 'Amazon' and $::operatingsystemmajrelease == '2015') {
          $releasever = '6'
        }
</pre>

**Comment by tobru** [comment]
Would you mind creating a PR for this changes?

**Comment by tobru** [comment]
@cagriersen Is this still an issue? If yes, would you mind creating a PR?

**Comment by tobru** [comment]
As I don't have an Amazon AMI available right now to test this issue and no tested PR has been made, I'll close this issue for now. If someone is able to provide a proper PR, I'm happy to merge it to have support for Amazon Linux.
