### ISSUE TITLE
Make sure apt-transport-https is installed on Debian OS

### ISSUE THREAD

**Issue by hirnschmalz** [vshn/puppet-gitlab#47]
To fetch packages from https sources the package `apt-transport-https` must be installed on the system (at least on Debian jessie).

**Comment by tobru** [comment]
I think that this doesn't belong into this module and should come from the Puppet infra. Feel free to reopen if you don't agree.

**Comment by hirnschmalz** [comment]
Sorry, but I think that this issue belongs to this module since almost every other apt source uses http. To use https apt sources the special package `apt-transport-https` is needed - which is not installed by default. So from my point of view if you install from https sources you should make sure that the required packages are installed.

**Comment by tobru** [comment]
Ok, will do it with `ensure_packages`
