### ISSUE TITLE
Add support for gitlab-workhorse configuration.

### ISSUE THREAD

**Issue by tunasalat** [vshn/puppet-gitlab#59]
GitLab 8.0 introduced gitlab-workhorse(https://gitlab.com/gitlab-org/gitlab-workhorse/blob/master/README.md) for HTTP requests, so there are gitlab_workhorse[] configurations available for gitlab.rb. Would be nice if this could be managed by the module.

**Comment by tobru** [comment]
Needs some new config sections: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template#L302

**Comment by tobru** [comment]
Done in #62
