### ISSUE TITLE
Failed to call refresh: Could not restart Service[gitlab-runsvdir]

### ISSUE THREAD

**Issue by cdenneen** [vshn/puppet-gitlab#64]
Gitlab 8.5.5
Module 1.8.0 release

On a fresh provision:

==> gitlab: Error: /Stage[main]/Gitlab::Service/Service[gitlab-runsvdir]: Failed to call refresh: Could not restart Service[gitlab-runsvdir]: Execution of '/usr/bin/gitlab-ctl restart' returned 1: ok: run: gitlab-workhorse: (pid 7493) 1s
==> gitlab: ok: run: logrotate: (pid 7499) 0s
==> gitlab: timeout: down: nginx: 0s, normally up, want up
==> gitlab: ok: run: postgresql: (pid 7573) 0s
==> gitlab: ok: run: redis: (pid 7582) 1s
==> gitlab: ok: run: sidekiq: (pid 7594) 0s
==> gitlab: ok: run: unicorn: (pid 7599) 0s
==> gitlab: Error: /Stage[main]/Gitlab::Service/Service[gitlab-runsvdir]: Could not restart Service[gitlab-runsvdir]: Execution of '/usr/bin/gitlab-ctl restart' returned 1: ok: run: gitlab-workhorse: (pid 7493) 1s
==> gitlab: ok: run: logrotate: (pid 7499) 0s
==> gitlab: timeout: down: nginx: 0s, normally up, want up
==> gitlab: ok: run: postgresql: (pid 7573) 0s
==> gitlab: ok: run: redis: (pid 7582) 1s
==> gitlab: ok: run: sidekiq: (pid 7594) 0s
==> gitlab: ok: run: unicorn: (pid 7599) 0s

Second provision is okay

**Comment by tobru** [comment]
What is your OS?

**Comment by cdenneen** [comment]
CentOS 7

**Comment by cdenneen** [comment]
@tobru still having issues with this.

**Comment by tobru** [comment]
As I only have Ubuntu machines here, I'm not really able to help at the moment. I'm sorry

**Comment by tobru** [comment]
As no one else stepped in to help here and I don't have a CentOS/RHEL environment the test, I'll close this issue for now. If it arises again, then feel free to open a new issue.
