### ISSUE TITLE
unrecognized option '--version'

### ISSUE THREAD

**Issue by cdenneen** [vshn/puppet-gitlab#65]
Not an error but just wanted to make note:

```
==> gitlab: Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns: /sbin/init: unrecognized option '--version'
==> gitlab: Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns: -.mount                                                                                   loaded active mounted   /
==> gitlab: Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]/returns: gitlab Reconfigured!
==> gitlab: Notice: /Stage[main]/Gitlab::Config/Exec[gitlab_reconfigure]: Triggered 'refresh' from 1 events
```

**Comment by tobru** [comment]
Do you have some information about versions used? OS, Gitlab, Puppet, ...

**Comment by cdenneen** [comment]
CentOS 7
Gitlab 8.5.5
Puppet 4.2.1

**Comment by seefood** [comment]
same here, plus gitlab-secrets.json keeps getting rewritten (but maybe that's a separate bug).

CetOS 7.2, Puppet 4.5

My guess is the issue with init is that it's not sure what to do about systemd?

**Comment by tobru** [comment]
As we don't have a Puppet 4.x environment at this time, it's hard for me to debug this issue. Can't see where the option "--version" comes from.

**Comment by seefood** [comment]
during the omnibus reconfigure:
```
/sbin/init: unrecognized option '--version'
-.mount                                          loaded active     mounted      /
```
Seems like the omnibus needs to be acquainted with systemd on CentOS/RHEL 7+. Nothing to do with the puppet module's code.

**Comment by tobru** [comment]
Can you run Puppet with `--debug`?

**Comment by tobru** [comment]
Yeah, I also think it's not related to the Puppet module. Let's close it for now.
