### ISSUE TITLE
gitlab::gitlab_rails hash merge not working

### ISSUE THREAD

**Issue by cdenneen** [vshn/puppet-gitlab#66]
I believe the issue is how this is being read in vs actually merging the data because hiera works fine.

**Comment by cdenneen** [comment]
Here is the fix:
```puppet
  $gitlab_rails = hiera_hash('gitlab::gitlab_rails',$::gitlab::gitlab_rails)
```

**Comment by cdenneen** [comment]
Reason is explained here:
https://docs.puppetlabs.com/hiera/3.0/puppet.html#limitations

**Comment by tobru** [comment]
As a workaround you could create a "wrapper" module (f.e. profile_gitlab) which collects the needed information from Hiera using hiera_array() and pass it to the gitlab module...
