### ISSUE TITLE
Gitlab EE SMTP Config

### ISSUE THREAD

**Issue by AlexanderNZ** [vshn/puppet-gitlab#73]
Hi there,

I was just wondering if this module is able to configure gitlab such that it uses SMTP for a mail server rather than postfix?

I can't see where gitlab_rails is pulling values from, I just want to be able to implement the instructions here: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/smtp.md

I've tried passing the following as a gitlab_rails entry as per the readme:
```

{
    'smtp_enable' => true,
    'smtp_address' => 'mail.example.internal',
    'smtp_port' => 25,
    'smtp_domain' => example.net,
    'gitlab_email_from' => 'gitlab@example.net',
    'gitlab_email_reply_to' => 'gitlab@example.net',
  },
```
But puppet returns that it's a string and not a hash. I don't understand why it has said that as this is the same as
```
{
    'webhook_timeout' => 10,
    'gitlab_default_theme' => 2,
  },
``` 
which is in the readme.

Have I missed something?

Cheers

Alex

**Comment by tobru** [comment]
Could you please post the output of Puppet and your whole Puppet manifest here? Makes things easier to debug. Thanks.

**Comment by AlexanderNZ** [comment]
I ended up going with a different solution so I'm going to close this issue, cheers
