### ISSUE TITLE
Add support for Docker registry

### ISSUE THREAD

**Issue by tobru** [vshn/puppet-gitlab#74]
Add support for the new feature: Docker registry. See http://docs.gitlab.com/ce/administration/container_registry.html#container-registry-domain-configuration

**Comment by llauren** [comment]
I've created a patch for this, which i'll try to pull-request. I couldn't find the directives on how to do this, so i just tried my best. This'll be my first ever contribution to an open source project, so please be gentle :)

**Comment by tobru** [comment]
Thanks for the PR, merged. After testing it a new release will be made.
