### ISSUE TITLE
shortcut to SSL, anyone?

### ISSUE THREAD

**Issue by seefood** [vshn/puppet-gitlab#75]
since this is a private gitlab on a publicly hosted machine (out on AWS) I want SSL out of the box, so I thought I'd go with a module that will use Let's Encrypt to create my certificates. however there's a chicken and egg here - nginx won't run till I create the certs and the certs can't be created without a working webserver (that will also serve files from the disk), so unless I'm missing something...?

in order to automate this, I'd have to patch this module and make a PR. I'll happily do it on a less busy week. for now I'd love it if there's a shortcut solution that I'm missing (or I'll just manually bootstrap the first cert and fix this in June)

Thanks in advance!

**Comment by tobru** [comment]
This will be fixed in an upcoming Gitlab Omnibus release and then also supported by the Puppet module. You can track progress here (see comments for some hints how to do it atm) : https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1096
