### ISSUE TITLE
Will this puppet module be maintained? 

### ISSUE THREAD

**Issue by spuder** [vshn/puppet-gitlab#8]
@tobru I'm the author of the spuder/puppet-gitlab puppet module as mentioned here: 

https://about.gitlab.com/installation/

Because of the new onibus packaging. my puppet module is currently broken. 

I was planning on rewriting it, however it appears that you have already rewritten puppet gitlab to work with the new package cloud repos. 

I'm evaluating if I want to deprecate my module, and instead refer people to your module. What are your thoughts on referring people to your module?

**Comment by tobru** [comment]
@spuder Thanks for asking. Yes, we are planning to maintain this module in the future, it's already on heavy use on our company and we're actively maintaining it... So if you want it would be a honour if you would refer people to this Puppet Gitlab module.

**Comment by spuder** [comment]
Great, I'm going to think about it a little more before I pull the trigger, but I'll probably end up shutting my module down and sending people here. I'll also let the gitlab team that there is a new preferred puppet module.
