### ISSUE TITLE
Upgrade from CE to EE doesn't work without manual work

### ISSUE THREAD

**Issue by gdubicki** [vshn/puppet-gitlab#82]
At least on RHEL, as you use a single `yumrepo` resource with the same name for 2 different repos, when upgrading from CE to EE edition the Yum repo is not being updated and upgrade does not happen until you manually remove the old repo and do a `yum clean`.

I think it would be enough to add edition to `yumrepo` resource name but unfortunately I don't have time to create a PR right now, sorry.

**Comment by tobru** [comment]
Thanks for your suggestion. I don't have a CentOS/RHEL system near me right now, so I would appreciate help here from someone who is able to test the change and create a PR.

**Comment by dhollinger** [comment]
I'll take a look at this and get a PR going this week.

**Comment by tobru** [comment]
@dhollinger Did you have a chance to create a PR?

**Comment by dhollinger** [comment]
@tobru Crap, sorry.

I have not, ended up not having the time. I can try taking a look at it this week, if I don't have time (or if you already have something ready), I'll step away. Don't want to be the holdup to fixing this any longer.

Sorry again!

**Comment by dhollinger** [comment]
As I do my work, I've noticed that tests against the gitlab.rb file are failing since the merge of #100 

I should have a PR ready for this issue later today. If I have time, I'll try and fix the issues related to #100 as well
