### ISSUE TITLE
parametirize the repo path

### ISSUE THREAD

**Issue by seefood** [vshn/puppet-gitlab#86]
Got my gitlab on /, and I want it on a diffrerent partition, say /data. going over the code I don't see a way to pass that parameter to the omnibus. I'd move and symlink it, but gitlab would not run on a path with any part of the path being a symlink.

On that matter, can I get the entire /var/opt/gitlab move into /opt/gitlab/githome or any random path as needed?

**Comment by tobru** [comment]
Do you have some more details here? Documentation to the Gitlab Omnibus configuration parameter for that? What parameter are you looking for?

**Comment by tobru** [comment]
Here you are: https://github.com/vshn/puppet-gitlab/blob/master/manifests/init.pp#L101
And here: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/629def0a7a26e7c2326566f0758d4a27857b52a3/README.md#storing-git-data-in-an-alternative-directory

**Comment by seefood** [comment]
Oh duh. I was grepping for "repos_path"... Sorry.
