### ISSUE TITLE
gitlab-secrets.json is destroyed and recreated on every puppet run

### ISSUE THREAD

**Issue by seefood** [vshn/puppet-gitlab#87]
Sample dump at http://pastebin.com/v3J98Az2

Basically,  the http secret, cert and internal key, plus all the mattermost salts and keys, all get removed with every puppet run and immediately new ones are generated and added by the reconfigure, which was triggered by the fact the file was edited. this seems to me like a serious bug, the entire omnibus should not need to rerun and restart on every run.
Also, does that mean mattermost is getting installed? should I be able to access it? it's not linked in the gitlab UI and I don't see any service that looks like it's related getting started.

**Comment by tobru** [comment]
The secrets in the `gitlab::secrets` hash must be in the exact same order as in the JSON file as gitlab-ctl rewrites the file on every run. You can also leave the parameter blank, the file is not touched then. See https://github.com/vshn/puppet-gitlab/blob/master/manifests/config.pp#L101
Regarding Mattermost: Please consult the Gitlab documentation for that: http://docs.gitlab.com/omnibus/gitlab-mattermost/ It is fully supported by this Puppet module.
