### ISSUE TITLE
Add Beaker acceptance tests

### ISSUE THREAD

**Issue by petems** [vshn/puppet-gitlab#88]
Add beaker acceptance tests to Travis

Basic tests to make sure standard install works 👍

**Comment by tobru** [comment]
Hi @petems, are you willing to contribute them? I'll be happy to get a PR for that.

**Comment by petems** [comment]
Yep, I put this here to remind me to do it when I have some slack time, maybe this weekend? 😄

**Comment by petems** [comment]
@tobru So, depending on how many builds we want, this may increase Travis build times by 10-15 minutes. Right now I've added support for all the listed supported versions in the metadata.json (RHEL-ish 6/7, Ubuntu 12/14)
