### ISSUE TITLE
Updating Gitlab CE

### ISSUE THREAD

**Issue by Cosaquee** [vshn/puppet-gitlab#98]
Hi !

Thanks for your awesome module ! It works really nice and my only problem is how to manage Gitlab upgrade proccess ? Right now I have version 8.12.6 on my server. Version 8.13 is released and I want to upgrade my installation. 

Any chance that i can do it with help of this module or should i do it manually ?

**Comment by hypnotortoise** [comment]
What I normally do is this:
1. Sync GL version I [want](https://packages.gitlab.com/gitlab/gitlab-ce/) to local Repository.

2. Set `package_ensure` explicitly to the version I want to install when calling Gitlab class:

E.g. upgrade to v7.13.0 @ CentOS6:  ` class {"::gitlab": package_ensure => "gitlab-ce-7.13.0-ce.0.el6`

**Comment by tobru** [comment]
I guess there is no action to take in this issue for the Puppet module maintainers.
